

export const imagens = [
  // Animais reais
  {src: "assets/img/lontra.jpg",    tipo: "real", dica: "Foto tirada em habitat natural." },
  {src: "assets/img/Urso.jpg",      tipo: "real", dica: "Fotografia de vida selvagem." },
  {src: "assets/img/Coelho.jpg",    tipo: "real", dica: "Imagem documental real." },
  {src: "assets/img/Golfinho.jpg",   tipo: "real", dica: "Proporções naturais." },
  {src: "assets/img/Arraia.jpg",      tipo: "real", dica: "Textura e reflexos naturais." },
  {src: "assets/img/Coruja.jpg",      tipo: "real", dica: "Detalhes do plumagem e olhos." },
  {src: "assets/img/Girafa.jpg",      tipo: "real", dica: "Proporções e padrões naturais." },
  {src: "assets/img/Leao.jpg",      tipo: "real", dica: "Inserção do animal no ambiente com profundidade real." },
  {src: "assets/img/Lince.jpg",      tipo: "real", dica: "Cor do olho e e dimensões naturais." },
  {src: "assets/img/Alce.jpg",      tipo: "real", dica: "Sombras naturais." },
  {src: "assets/img/Arara.jpg",      tipo: "real", dica: "Cores e definições do corpo realistas." },
  {src: "assets/img/Zebra.jpg",      tipo: "real", dica: "Animal enserido no ambiente sem distorção e com profundidade real." },
  {src: "assets/img/Cavalo.jpg",      tipo: "real", dica: "Definição dos músculos e textura do pelagem." },
  {src: "assets/img/Tubaraobranco.jpg",      tipo: "real", dica: "Reflexos da água real." },
  {src: "assets/img/Cisne.jpg",      tipo: "real", dica: "Reflexos e detalhes de água naturais." },
  {src: "assets/img/Esquilo.jpg",      tipo: "real", dica: "Imagem com profundidade bem definida." },
  {src: "assets/img/Jacare.jpg",      tipo: "real", dica: "Sombras em disposição real." },
  {src: "assets/img/Marreco.jpg",      tipo: "real", dica: "Coloração e detalhes do bico realistas." },
  {src: "assets/img/Tigre.jpg",      tipo: "real", dica: "Ambiente com profundidade real." },

  // Animais gerados por IA
  {src: "assets/img/IALontra.png",  tipo: "fake", dica: "Textura do pelo é artificialmente uniforme." },
  {src: "assets/img/IAUrso.png",    tipo: "fake", dica: "Fundo e iluminação inconsistentes." },
  {src: "assets/img/IACoelho.png",  tipo: "fake", dica: "Olhos e orelhas com proporções artificiais." },
  {src: "assets/img/IAGolfinho.png", tipo: "fake", dica: "Reflexos e detalhes de água pouco naturais." },
  {src: "assets/img/IAArraia.png",   tipo: "fake", dica: "Contorno exagerado." },
  {src: "assets/img/IACoruja.png",   tipo: "fake", dica: "Detalhes de plumagem e olhos artificiais." },
  {src: "assets/img/IAGirafa.png",   tipo: "fake", dica: "Proporções e padrões gerados artificialmente." },
  {src: "assets/img/IALeao.png",   tipo: "fake", dica: "Ambiente com profundidade artificial." },
  {src: "assets/img/IALince.png",   tipo: "fake", dica: "Olhos e pelagem artificiais." },
  {src: "assets/img/IAAlce.png",   tipo: "fake", dica: "Reflexos da água pouco naturais." },
  {src: "assets/img/IAArara.png",   tipo: "fake", dica: "Cores e definições do corpo artificiais." },
  {src: "assets/img/IAZebra.png",   tipo: "fake", dica: "Cor do animal e do ambiente diferentes." },
  {src: "assets/img/IACavalo.png",   tipo: "fake", dica: "Animal enserido com distorção." },
  {src: "assets/img/IATubaraobranco.png",   tipo: "fake", dica: "Passagem da luz artificial." },
  {src: "assets/img/IACisne.png",   tipo: "fake", dica: "Reflexos na água não são realistas." },
  {src: "assets/img/IAEsquilo.png",   tipo: "fake", dica: "Diferença nas patas do animal." },
  {src: "assets/img/IAJacare.png",   tipo: "fake", dica: "Animal enserido na água de forma artificial." },
  {src: "assets/img/IAMarreco.png",   tipo: "fake", dica: "Cores e reflexos artificiais." },
  {src: "assets/img/IATigre.png",   tipo: "fake", dica: "Cores e listras artificiais." },

];
